import { chromium } from 'playwright';
const SP = '/tmp/claude-0/-home-user-PlanetEscape/df760632-f5e3-5f5f-b0a9-49fe681eb24b/scratchpad';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1400, height: 860 }, locale: 'de-DE' });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.addInitScript(() => localStorage.setItem('pe_lang', 'de'));
await page.goto('http://localhost:4179/', { waitUntil: 'load' });
await page.waitForSelector('[data-act="playview"]', { timeout: 15000 });
await page.click('[data-act="playview"]');
await page.waitForSelector('[data-example="logistics"]');
await page.click('[data-example="logistics"]');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${SP}/ui-modal.png` });
const close = await page.$('.modal [data-act="close"]');
if (close) await close.click();
await page.waitForTimeout(3000);
await page.click('[data-act="pause"]');
await page.waitForTimeout(400);
await page.screenshot({ path: `${SP}/ui-top.png`, clip: { x: 0, y: 0, width: 1400, height: 280 } });
await page.click('[data-act="menu"]');
await page.waitForTimeout(600);
await page.screenshot({ path: `${SP}/ui-menu.png` });
await browser.close();
