import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.addInitScript(() => {
  localStorage.setItem('pe_intro_seen', '1'); localStorage.setItem('pe_lang', 'de');
  window.__log = [];
  const o = AudioParam.prototype.setTargetAtTime;
  AudioParam.prototype.setTargetAtTime = function (v, t, c) { window.__log.push(+v.toFixed(3)); return o.call(this, v, t, c); };
  window.__osc = 0;
  const co = AudioContext.prototype.createOscillator;
  AudioContext.prototype.createOscillator = function () { window.__osc++; return co.call(this); };
});
await p.goto('http://localhost:4272/');
await p.waitForTimeout(1200);
await p.mouse.click(5, 5);
await p.waitForTimeout(500);
await p.click('[data-act="settingsview"]');
await p.waitForTimeout(600);
await p.evaluate(() => { window.__log = []; });
const s = await p.$('input[data-vol="music"]');
const box = await s.boundingBox();
await p.mouse.click(box.x + 3, box.y + box.height / 2);
await p.waitForTimeout(300);
console.log('fader to 0 -> gain targets', await p.evaluate(() => JSON.stringify(window.__log)));
await p.mouse.click(box.x + box.width * 0.6, box.y + box.height / 2);
const names = [];
for (let i = 0; i < 5; i++) {
  names.push(await p.evaluate(() => document.querySelector('.set-song b').textContent));
  await p.click('[data-act="music-next"]');
  await p.waitForTimeout(400);
}
console.log('menu songs:', names.join(' | '));
await p.screenshot({ path: 'x-m1.png', clip: { x: 60, y: 300, width: 520, height: 140 } });
await p.evaluate(() => window.__pe.hud.cb.onNewGame(5, { mode: 'free', mapSize: 'medium', infiniteOre: false, allUnlocked: false, storms: true }));
await p.waitForTimeout(1000);
const o1 = await p.evaluate(() => window.__osc);
await p.waitForTimeout(6000);
console.log('game osc in 6s', (await p.evaluate(() => window.__osc)) - o1);
console.log('errors', errs);
await b.close();
